# Disabling feat
AUDIO_ENABLE = no
MOUSEKEY_ENABLE = no
CONSOLE_ENABLE = no
ENCODER_ENABLE = no
POINTING_DEVICE_ENABLE = no
ANALOG_JOYSTICK_ENABLE = no

# Ensure features are activated
LTO_ENABLE = yes
OLED_ENABLE = yes
TRI_LAYER_ENABLE = yes
